// Alt text for every survey photo — source: 유찬님 '사진영문설명' 시트 (8/15).
// The sheet is keyed on the original Korean filenames; this file is the same
// text re-keyed to the filenames actually deployed under public/photos.
// Screen readers read these sentences, so they describe what is in the photo.
// 25 photos (YS06 x18, ST09 x7) are still awaiting a description in the sheet;
// they fall back to a generic sentence in PHOTO_ALT_FALLBACK.

export const PHOTO_ALT: Record<string, string> = {
  "GH01_audio-guide_01.jpg": "Audio guide rental counter with mobile guide instructions",
  "GH01_bag-service_01.jpg": "Information sign for the accessibility bag rental service",
  "GH01_elevator_01.jpg": "Elevator entrance and directional sign inside the building",
  "GH01_entrance_01.jpg": "Main entrance facade with stone arches of the museum",
  "GH01_nursery_01.jpg": "Entrance to the kids room and nursing room",
  "GH01_restroom_01.jpg": "Accessible restroom doors on the first floor",
  "GH01_restroom_02.jpg": "Men's accessible restroom sign and entrance on the basement level",
  "GH01_restroom_03.jpg": "Women's accessible restroom sign on the basement level",
  "GH01_slope_01.jpg": "Sloped stone-paved pathway through the garden",
  "GH01_slope_02.jpg": "Sloped stone pathway leading toward the museum",
  "GH01_slope_03.jpg": "Sloped approach road to the front entrance",
  "GH01_slope_04.jpg": "Sloped pedestrian path leading to the museum grounds",
  "GH02_access-info_01.jpg": "Directional sign indicating the stroller and wheelchair route",
  "GH02_access-info_02.jpg": "Accessible route guidance sign detailing tour information",
  "GH02_access-info_03.jpg": "Information sign providing accessibility contact details for visitors with limited mobility",
  "GH02_elevator_01.jpg": "Exterior glass elevator providing step-free access near Seokjojeon Hall",
  "GH02_entrance_01.jpg": "Daehanmun Gate, the main entrance of Deoksugung Palace",
  "GH02_gravel_01.jpg": "Stone-paved yard and pathway in front of Junghwajeon Hall",
  "GH02_guide-service_01.jpg": "Guided tour information sign at Deoksugung Palace",
  "GH02_guide-service_02.jpg": "Seokjojeon Hall tour reservation and ticketing sign",
  "GH02_nursing-room_01.jpg": "Baby lounge facility building with a wooden deck",
  "GH02_office_01.jpg": "Palace management office building inside the grounds",
  "GH02_restroom_01.jpg": "Exterior view of the accessible restroom building at Deoksugung Palace",
  "GH02_slope_01.jpg": "Sloped paved pathway leading to Dondeokjeon Hall",
  "GH02_slope_02.jpg": "Wooden ramp and pathway structure near Dondeokjeon Hall",
  "GH02_slope_03.jpg": "Wooden accessibility ramp installed in front of the building",
  "GH02_slope_04.jpg": "Wooden accessibility ramp installed near Junghwajeon Hall",
  "GH02_step_01.jpg": "Fall hazard warning sign near the courtyard",
  "GH03_entrance_01.jpg": "Spring sculpture landmark at the entrance of Cheonggye Plaza",
  "GH03_slope_01.jpg": "Sloped walkway inside the underground passage near Cheonggye Plaza",
  "GH05_ground_01.jpg": "Ground level view of the Garden of Gratitude",
  "GH05_stairs_01.jpg": "Staircase leading to the underground exhibition hall",
  "GH06_door_01.jpg": "Glass entrance door of the museum",
  "GH07_elevator_01.jpg": "Exterior elevator providing step-free access",
  "GH07_ramp_01.jpg": "Wooden ramp leading to the museum entrance",
  "GH08_detour_01.jpg": "Alternative dirt path bypassing the stone-paved yard",
  "GH08_stairs_01.jpg": "Stone stairs leading up to Geunjeongjeon Hall",
  "GH08_stone-pavement_01.jpg": "Uneven stone-paved yard in front of Geunjeongjeon Hall",
  "GH09_door_01.jpg": "Glass entrance doors of the museum",
  "GH10_door_01.jpg": "Automatic glass entrance door of MMCA Seoul",
  "ST01_elevator_01.jpg": "Interior elevator entrance (Unit 1) at City Hall Station",
  "ST01_elevator_02.jpg": "Interior elevator entrance (Unit 2) at City Hall Station",
  "ST01_elevator_03.jpg": "Exterior elevator entrance (Unit 1) at City Hall Station",
  "ST01_restroom_01.jpg": "Directional sign and entrance to the accessible restrooms at City Hall Station",
  "ST02_elevator_01.jpg": "Interior elevator entrance (Unit 1) at City Hall Station",
  "ST02_elevator_02.jpg": "Exterior elevator entrance (Unit 1) at City Hall Station",
  "ST02_restroom_01.jpg": "Entrance to the accessible men's restroom at City Hall Station",
  "ST02_restroom_02.jpg": "Entrance to the accessible women's restroom with tactile paving at City Hall Station",
  "ST02_slope_01.jpg": "Street view and pathway seen from the opened elevator at City Hall Station",
  "YS04_level_01.jpg": "Inclinometer app showing -6 degrees for slope measurement",
  "YS04_level_02.jpg": "Inclinometer app showing slope angle measurement",
  "YS04_level_03.jpg": "Inclinometer app showing -13 degrees for slope measurement",
  "YS04_restroom_01.jpg": "Interior view of the accessible restroom with grab bars",
  "YS04_restroom_02.jpg": "Entrance view of the accessible restroom with tactile paving",
  "YS04_restroom_03.jpg": "Exterior view of the accessible restroom building",
  "YS04_slope_01.jpg": "Sloped walking path surrounded by trees",
  "YS04_slope_02.jpg": "Paved walking trail through the forested area",
  "YS04_slope_03.jpg": "Sloped pathway section within the park",
  "YS04_step_01.jpg": "Paved walkway alongside drainage stones and grass",
  "YS04_step_02.jpg": "Directional signpost and pathway view in the park",
  "YS04_step_03.jpg": "Measuring tape showing a level difference of 2.5 cm on the path",
  "YS04_step_04.jpg": "Speed bump and cable protector installed on the pathway",
};

export const photoAlt = (file: string, placeName: string) =>
  PHOTO_ALT[file] ?? `${placeName}, photographed during our on-site accessibility survey`;
